In [13]:
import sys, os
sys.path.append(os.path.abspath('..'))

import pandas as pd
import mlflow
from src.mlflow_setup import init_tracking

init_tracking()

model_uri = "models:/walmart_sales_best_model/2"
model = mlflow.pyfunc.load_model(model_uri)

print("Model loaded")

Downloading artifacts: 100%|██████████| 5/5 [00:06<00:00,  1.29s/it]

Model loaded

In [14]:
test = pd.read_csv('../data/test.csv')
print(test.shape)
test.head()

(115064, 4)

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [15]:
predictions = model.predict(test)
print(predictions[:10])

[38689.285 11669.934 13192.261 22279.771 15793.302 14414.234 14823.575
 14657.208 19580.686 11857.803]

In [10]:
submission = pd.DataFrame({
    'Id': test['Store'].astype(str) + '_' + test['Dept'].astype(str) + '_' + test['Date'].astype(str),
    'Weekly_Sales': predictions
})

submission.head()

               Id  Weekly_Sales
0  1_1_2012-11-02   2653.471680
1  1_1_2012-11-09   1067.372681
2  1_1_2012-11-16   2636.042480
3  1_1_2012-11-23   3926.470703
4  1_1_2012-11-30   4565.464844

In [16]:
submission.to_csv('../data/submission.csv', index=False)
print("Saved submission.csv")

Saved submission.csv

In [17]:
mlflow.set_experiment("XGBoost_Training")

with mlflow.start_run(run_name="XGBoost_kaggle_submission"):
    mlflow.log_param("model_version", 1)
    mlflow.log_param("submission_file", "submission.csv")
    mlflow.log_artifact('../data/submission.csv')
    print("Submission logged")

Submission logged
🏃 View run XGBoost_kaggle_submission at: https://dagshub.com/ekali-star/walmart-recruiting.mlflow/#/experiments/1/runs/d1be1471b27e4d8aaa6e1b5303ee537a
🧪 View experiment at: https://dagshub.com/ekali-star/walmart-recruiting.mlflow/#/experiments/1

In [18]:
submission = pd.DataFrame({
    'Id': test['Store'].astype(str) + '_' + test['Dept'].astype(str) + '_' + test['Date'].astype(str),
    'Weekly_Sales': predictions
})

submission.to_csv('../data/submission_v2.csv', index=False)
print("Saved submission_v2.csv")

Saved submission_v2.csv